package com.caito.security01.utils.enums;

public enum RolePermission {
    READ_ALL_PRODUCT,
    READ_ONE_PRODUCT,
    CREATE_ONE_PRODUCT,
    UPDATE_ONE_PRODUCT,
    DISABLE_ONE_PRODUCT,
    READ_ALL_CATEGORY,
    READ_ONE_CATEGORY,
    CREATE_ONE_CATEGORY,
    UPDATE_ONE_CATEGORY,
    DISABLE_ONE_CATEGORY,
    READ_MY_PROFILE;
}
